### ISSUE TITLE
Bot should send emails when the corresponding tag is added

### ISSUE THREAD

**Issue by paulb777** [firebase/oss-bot#2]
Bot should send emails when the corresponding tag is added in addition to when the issue is later updated.

**Comment by samtstern** [comment]
@paulb777 same here as in #3 this is already the intended behavior I believe we were not seeing this before because of a functions crash.

**Comment by samtstern** [comment]
Note: emails will not be delivered to `@google.com` groups unless they are configured to take emails from the public.  This is required since I don't know of any way to get the bot an @google.com email address/

**Comment by paulb777** [comment]
@samstern Looks like it's still not working. @davidair set up a publicly configured https://groups.google.com/a/google.com/forum/#!forum/icore-eng-github and it hasn't received any emails despite multiple Core tags including https://github.com/firebase/firebase-ios-sdk/issues/58

**Comment by samtstern** [comment]
This is definitely fixed now (I get a lot of these emails through Firestore).

If you're not getting the emails check group spam settings.
