### ISSUE TITLE
Bot should not add "needs-triage" tag to feature requests

### ISSUE THREAD

**Issue by jshcrowthe** [firebase/oss-bot#4]
Feature requests don't typically follow the issue template (in my experience that is), because issue templates are typically geared more towards bugs. This makes it hard to predictably parse the issue meaning a lot of duplicate "needs triage" messages.

I'd propose, for feature requests, we don't worry about the auto-assigning beyond classifying it as a feature request. We can then route it or further classify as need be, but feature requests already have to be human triaged so it feels like a duplicate tag.

**Comment by samtstern** [comment]
Addressed in 8b53f18, will push later today.
