### ISSUE TITLE
Apply a label when template validation fails.

### ISSUE THREAD

**Issue by samtstern** [firebase/oss-bot#49]
When the template fails to validate we could apply a label like `needs-triage` or `needs-more-info`.

Open questions:

- [ ] Should this label name be configurable per repo?  If so, what is the config format?
- [ ] Should this be in addition to the comment or instead of the comment?

**Comment by marcbaechinger** [comment]
1) Having a good default would be a chance for the bot to bring consistency across the repositories managed with the bot. On the other hand there should be the option for configuring the label. Be together, not the same. :)

2) For the ExoPlayer repository it should be in addition to the comment. The comment gives a clear hint to the reporter, while the label can be more easily overlooked.
