### ISSUE TITLE
Create an "admin" view for bot auditing

### ISSUE THREAD

**Issue by samtstern** [firebase/oss-bot#50]
Right now we have to dig into the logs to see what happened for a certain issue.  We should log the actions the bot takes and **WHY** it takes them in some easy-to-view interface.

**Comment by samtstern** [comment]
Things it should tell you about:

- Why it reported a non-matching template
- Why it matched a particular label
- Why it moved around the stale cycle

**Comment by samtstern** [comment]
This can probably be implemented by adding a "reason" string field to the existing Github Action system and then logging all actions and reasons.

**Comment by samtstern** [comment]
This is being addressed in #51

**Comment by samtstern** [comment]
Demo:
https://ossbot.computer/audit.html?org=google&repo=ExoPlayer

**Comment by samtstern** [comment]
Some suggestions from Marc

```
1) The target col could link back to the issue
2) If a row has an id something like 

    id="invalid_template_5530"
    id="close_5530"
    id="label_5530"
    
a link with a hash would directly jump to that row:

   https://ossbot.computer/audit.html?org=google&repo=ExoPlayer#invalid_template_5530

That would be useful for us project members, when an issue has been marked as invalid.
If desired we could even add that link to the bot comment, so reporters can navigate to a more detailed reasons of rejection themselves.
```

**Comment by samtstern** [comment]
We now have better reasons and links directly to rows:
![image](https://user-images.githubusercontent.com/8466666/54048201-f4840e00-418d-11e9-9384-c266a9945e1f.png)

**Comment by samtstern** [comment]
@marchbaecinger here's an example of a permalink to an audit log entry:
https://ossbot.computer/audit.html?org=google&repo=ExoPlayer&key=-L_STGWF1EE3IMxuR0gM

The reasons will be better from here forward, I can't retroactively improve the old ones

**Comment by marcbaechinger** [comment]
Oh, woow! Amazing! Many thanks!  :)
From our side no need to backfill the reasons.
