### ISSUE TITLE
Links in weekly report of ExoPlayer needs the organisation replaced

### ISSUE THREAD

**Issue by marcbaechinger** [firebase/oss-bot#54]
The links of issues in the email report of non-firebase repositories still use 'firebase' as the organisation and produce a 404.

The URL would need to have 'firebase' replaced with 'google' in the case of the exoplayer repository:

https://github.com/firebase/exoplayer/issues/5568

It seems to me that report.ts can already deal with the org but the org for GetWeeklyEmail is hardcoded to 'firebase':

https://github.com/firebase/oss-bot/blob/master/functions/src/report.ts#L459
https://github.com/firebase/oss-bot/blob/master/functions/src/report.ts#L568

**Comment by samtstern** [comment]
Should be fixed by https://github.com/firebase/oss-bot/commit/4a24cc6e78e1e53c1c927725a6cab32470258404

**Comment by marcbaechinger** [comment]
Ha! I want to see the SAM score of this repo! :D
