### ISSUE TITLE
FR: Lock issues after they are fixed

### ISSUE THREAD

**Issue by samtstern** [firebase/oss-bot#56]
@wilhuff proposed a feature for the bot to lock issues when conversation is no longer productive.  It would probably involve the bot leaving a comment like:

> Hey everyone.  It has been {time interval} since this issue was fixed so I am locking the thread.  If you're still having problems please open a new issue (link) and we're happy to discuss.

The main to-do here is to determine the criteria for locking.  Should we just do closed for {x} time?  Should we require a special label?  A milestone?

**Comment by paulb777** [comment]
Why not use the github ui?

**Comment by samtstern** [comment]
Gil would like to do this automatically after some period of time post-closing to leave time for people to chime in about short-term regressions, I think.

**Comment by paulb777** [comment]
Oh, to force people to open new issues instead of adding semi-similar issues to closed existing issues?  That would be useful - maybe only for closed with a merge versus closed for staleness? @wilhuff

**Comment by wilhuff** [comment]
Yeah, twice in the last two weeks I've had to prompt people to open new issues for things we fixed months ago. In one case a few weeks back, the issue was almost a year old and someone posted, "me too".
