### ISSUE TITLE
weekdays check is not working

### ISSUE THREAD

**Issue by paulb777** [firebase/oss-bot#90]
Here's an issue that was marked stale on Sunday November 29th and closed on Saturday December 5th - https://github.com/firebase/firebase-ios-sdk/issues/7006#issuecomment-739443579

**Comment by samtstern** [comment]
On 11/29 the bot said:

```
Hey xxx. We need more information to resolve this issue but there hasn't been an update in 5 weekdays. I'm marking the issue as stale and if there are no new updates in the next 5 days I will close it automatically.

If you have more information that will help us get to the bottom of this, just add a comment!
```

Then on 12/5:

```
ince there haven't been any recent updates here, I am going to close this issue.

@vijayvishesh if you're still experiencing this problem and want to continue the discussion just leave a comment here and we are happy to re-open this.
```

The days in between are:

- 11/29 (Weekend)
- 11/30 (Weekday 1)
- 12/01 (Weekday 2)
- 12/02 (Weekday 3)
- 12/03 (Weekday 4)
- 12/04 (Weekday 5)
- 12/05 (Weekend)

That seems correct to me? 5 weekdays passed in between.

**Comment by paulb777** [comment]
I suppose that's technically true.  However, it seems like it's missing some of the point to send the notices on the weekend and disrupt INBOXes. The first notice should be sent on Monday and the second on the next weekday after 5 weekdays have passed which is the following Monday.

**Comment by samtstern** [comment]
I see, the goal of the current implementation was about making sure that everyone had the same amount of working days to respond. So even if the bot says something on the weekend, your days don't start counting down until Monday.

So you're saying the bot should just be quiet on weekends?

**Comment by paulb777** [comment]
Yes, to be conscientious about disrupting people's weekends with notices - although I suppose that doesn't completely scale worldwide.
